<a href="https://colab.research.google.com/github/Hamshaa/Panda/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=[10,11,12,13]
a.append(14)
print(a)

[10, 11, 12, 13, 14]


In [ ]:
a.pop()
print(a)

[10, 11, 12, 13]


In [ ]:
a.insert(2,4)
print(a)

[10, 11, 4, 12, 13]


In [ ]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
import numpy as np
arr=numpy.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


In [ ]:
import numpy as np
a=np.ones(3)
print(a)

[1. 1. 1.]


In [ ]:
a=np.random.random((3,2))
print(a)

[[0.14547827 0.42862348]
 [0.53059695 0.72458681]
 [0.24427139 0.00786715]]


In [ ]:
c=np.eye(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a=np.ones((4,3,2))
print(a)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
a=[1,2,3,4]
print(a[0:2])

[1, 2]


In [ ]:
print(a[1:])

[2, 3, 4]


In [ ]:
a=np.array([1,2,3,4])
print(a[0:1])

[1]


In [ ]:
a=np.array([[1,2],[3,4],[5,6]])
print(a[0:2,0])

[1 3]


In [ ]:
print(a[1:3])

[[3 4]
 [5 6]]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[1:3,2:4])

[[ 7  8]
 [11 12]]


In [ ]:
row_r1=a[1,:]
row_r2=a[1:2,:]
row_r3=a[[1],:]
print(row_r1,row_r1.shape)
print(row_r2,row_r2.shape)
print(row_r3,row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
col_c1=a[:,1]
col_c2=a[:,1:2]
print(col_c1,col_c2.shape)
print(col_c2,col_c2.shape)

[ 2  6 10] (3, 1)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [ ]:
import numpy as np
a=np.array([1,8,9,-3,2,4,7,9])
print(np.argmax(a))


2


In [ ]:
print(np.argsort(a))

[3 0 4 5 6 1 2 7]


In [ ]:
a=[0]
a=np.append(a,[1,2,3,4])
print(a)

[0 1 2 3 4]


In [ ]:
a=np.delete(a,[2,3])
print(a)

[0 1 4]


In [ ]:
a=np.array([[3,2,1],[6,5,4],[9,8,7]])
a=np.sort(a,axis=1,kind="quicksort")
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x=np.array([1,2])
y=np.array([1,0])
print(x.dot(y))

1


In [ ]:
a=np.array([[1,2],[3,4]])
print(a.T)

[[1 3]
 [2 4]]


In [ ]:
a=np.array(([1,2,3,4]))
s=a.squeeze()
print(s)

[1 2 3 4]


In [ ]:
import pandas as pd
import numpy as np
a=np.array([10,11,12,13,14])
type(a)

numpy.ndarray

In [ ]:
s=pd.Series([10,11,12,13,14])
type(s)

pandas.core.series.Series

In [ ]:
s

0    10
1    11
2    12
3    13
4    14
dtype: int64

In [ ]:
s[3]

13

In [ ]:
s

0    10
1    11
2    12
dtype: int64

In [ ]:
s.drop(2)

0    10
1    11
dtype: int64

In [ ]:
s[2]

12

In [ ]:
s.drop(2,inplace=True)
s[2]

KeyError: ignored

In [ ]:
s.iloc[1]

11

In [ ]:
s.loc[1]

11

In [ ]:
s.index

Int64Index([0, 1], dtype='int64')

In [ ]:
ss=pd.Series([10,12,13,44,56],index=['a','b','c','d','e'])
ss

a    10
b    12
c    13
d    44
e    56
dtype: int64

In [ ]:
ss.loc['a']

10

In [ ]:
data=[['Alex',10,'23-05-2000'],['Bob',None,None],['Clarke',None,'23-05-2000']]
data

[['Alex', 10, '23-05-2000'],
 ['Bob', None, None],
 ['Clarke', None, '23-05-2000']]

In [ ]:
df=pd.DataFrame(data)
df

0     1           2
0    Alex  10.0  23-05-2000
1     Bob   NaN        None
2  Clarke   NaN  23-05-2000

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df, *[1], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df, *[1], **{})
chart

import numpy as np
from google.colab import autoviz

def categorical_histogram(df, colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  df.groupby(colname).size().plot(kind='barh', color=sns.palettes.mpl_palette(mpl_palette_name), figsize=(8*figscale, 4.8*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(df, *[0], **{})
chart

import numpy as np
from google.colab import autoviz

def categorical_histogram(df, colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  df.groupby(colname).size().plot(kind='barh', color=sns.palettes.mpl_palette(mpl_palette_name), figsize=(8*figscale, 4.8*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(df, *[2], **{})
chart

import numpy as np
from google.colab import autoviz

def heatmap(df, x_colname, y_colname, figscale=1, mpl_palette_name='viridis'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  import pandas as pd
  plt.subplots(figsize=(8 * figscale, 8 * figscale))
  df_2dhist = pd.DataFrame({
      x_label: grp[y_colname].value_counts()
      for x_label, grp in df.groupby(x_colname)
  })
  sns.heatmap(df_2dhist, cmap=mpl_palette_name)
  plt.xlabel(x_colname)
  plt.ylabel(y_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = heatmap(df, *[0, 2], **{})
chart

import numpy as np
from google.colab import autoviz

def violin_plot(df, value_colname, facet_colname, figscale=1, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (12 * figscale, 1.2 * figscale * len(df[facet_colname].unique()))
  plt.figure(figsize=figsize)
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(df, *[1, 0], **{'inner': 'stick'})
chart

import numpy as np
from google.colab import autoviz

def violin_plot(df, value_colname, facet_colname, figscale=1, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (12 * figscale, 1.2 * figscale * len(df[facet_colname].unique()))
  plt.figure(figsize=figsize)
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(df, *[1, 2], **{'inner': 'stick'})
chart

In [ ]:
df[0:1]

0     1           2
0  Alex  10.0  23-05-2000

In [ ]:
df[0:2]

0     1           2
0  Alex  10.0  23-05-2000
1   Bob   NaN        None

In [ ]:
df[0:3]

0     1           2
0    Alex  10.0  23-05-2000
1     Bob   NaN        None
2  Clarke   NaN  23-05-2000

In [ ]:
df[0][0]

'Alex'

In [ ]:
df[0]

0      Alex
1       Bob
2    Clarke
Name: 0, dtype: object

In [ ]:
df[1:2]

0   1     2
1  Bob NaN  None

In [ ]:
df=pd.DataFrame(data,columns=['First Name','Age','DOB'])
df

First Name   Age         DOB
0       Alex  10.0  23-05-2000
1        Bob   NaN        None
2     Clarke   NaN  23-05-2000

In [ ]:
df['First Name']

0      Alex
1       Bob
2    Clarke
Name: First Name, dtype: object

In [ ]:
df.loc[0,'First Name']

'Alex'

In [ ]:
df.iloc[0,0]

'Alex'

In [ ]:
df['First Name'][0]

'Alex'

In [ ]:
df.isnull().sum()

First Name    0
Age           2
DOB           1
dtype: int64

In [ ]:
data=[['Alex',10,'23-05-2000'],['Bob',None,None],['Clarke',None,'23-05-2000'],['Hams',None,None],['Kari',None,None]]
data

[['Alex', 10, '23-05-2000'],
 ['Bob', None, None],
 ['Clarke', None, '23-05-2000'],
 ['Hams', None, None],
 ['Kari', None, None]]

In [ ]:
df=pd.DataFrame(data)
df

0     1           2
0    Alex  10.0  23-05-2000
1     Bob   NaN        None
2  Clarke   NaN  23-05-2000
3    Hams   NaN        None
4    Kari   NaN        None

In [ ]:
df.dropna()

0     1           2
0  Alex  10.0  23-05-2000

In [ ]:
df.dropna(inplace=True)
df

0     1           2
0  Alex  10.0  23-05-2000

In [ ]:
df1=pd.DataFrame(data,columns=['First Name','Age','DOB'])
df1

First Name   Age         DOB
0       Alex  10.0  23-05-2000
1        Bob   NaN        None
2     Clarke   NaN  23-05-2000
3       Hams   NaN        None
4       Kari   NaN        None

In [ ]:
df1.drop(['Age'],axis=1,inplace=True)
df1

KeyError: ignored

In [ ]:
df1.drop([0,2])

KeyError: ignored

In [ ]:
import numpy as np
a=np.array([10,12,13,44,56])
a>40

array([False, False, False,  True,  True])

In [ ]:
a[a>40]

array([44, 56])

In [ ]:
a[a%2!=0]

array([13])

In [ ]:
df

First Name   Age         DOB
0       Alex  10.0  23-05-2000
1        Bob   NaN        None
2     Clarke   NaN  23-05-2000
3       Hams   NaN        None
4       Kari   NaN        None

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   First Name  5 non-null      object 
 1   Age         1 non-null      float64
 2   DOB         2 non-null      object 
dtypes: float64(1), object(2)
memory usage: 248.0+ bytes


In [ ]:
df['First Name'].str.contains('e')

0     True
1    False
2     True
3    False
4    False
Name: First Name, dtype: bool

In [ ]:
df['First Name'].str.contains('b')

0    False
1     True
2    False
3    False
4    False
Name: First Name, dtype: bool

In [ ]:
df['First Name'].str.contains('a')

0    False
1    False
2     True
3     True
4     True
Name: First Name, dtype: bool

In [ ]:
print(df.shape)
print(df.size)
print(df.axes)
print(df.ndim)
print(df.dtypes)
print(df.index)
print(df.columns)
print(df.values)

(5, 3)
15
[RangeIndex(start=0, stop=5, step=1), Index(['First Name', 'Age', 'DOB'], dtype='object')]
2
First Name     object
Age           float64
DOB            object
dtype: object
RangeIndex(start=0, stop=5, step=1)
Index(['First Name', 'Age', 'DOB'], dtype='object')
[['Alex' 10.0 '23-05-2000']
 ['Bob' nan None]
 ['Clarke' nan '23-05-2000']
 ['Hams' nan None]
 ['Kari' nan None]]


In [ ]:
df.tail()

First Name   Age         DOB
0       Alex  10.0  23-05-2000
1        Bob   NaN        None
2     Clarke   NaN  23-05-2000
3       Hams   NaN        None
4       Kari   NaN        None

In [ ]:
df.describe()

Age
count   1.0
mean   10.0
std     NaN
min    10.0
25%    10.0
50%    10.0
75%    10.0
max    10.0

In [ ]:
df2=pd.concat([df,df])
df2

First Name   Age         DOB
0       Alex  10.0  23-05-2000
1        Bob   NaN        None
2     Clarke   NaN  23-05-2000
3       Hams   NaN        None
4       Kari   NaN        None
0       Alex  10.0  23-05-2000
1        Bob   NaN        None
2     Clarke   NaN  23-05-2000
3       Hams   NaN        None
4       Kari   NaN        None

In [ ]:
df['First Name']

0      Alex
1       Bob
2    Clarke
3      Hams
4      Kari
Name: First Name, dtype: object

In [ ]:
df.DOB

0    23-05-2000
1          None
2    23-05-2000
3          None
4          None
Name: DOB, dtype: object

In [ ]:
df['DOB'][0]

'23-05-2000'

In [ ]:
df.loc[0][0]

'Alex'

In [ ]:
df.loc[0,'First Name']

'Alex'

In [ ]:
df.iloc[0,0]

'Alex'

In [ ]:
df.iloc[0,1]

10.0

In [ ]:
df['DOB'][1]='30-3-2004'
df

<ipython-input-101-7afce3d3bf3f>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DOB'][1]='30-3-2004'


First Name   Age         DOB
0       Alex  10.0  23-05-2000
1        Bob   NaN   30-3-2004
2     Clarke   NaN  23-05-2000
3       Hams   NaN        None
4       Kari   NaN        None

In [ ]:
import pandas as pd
df=pd.read_html("https://en.wikipedia.org/wiki/Tab-separated_values")
df

[                               0  \
 0                            NaN   
 1             Filename extension   
 2            Internet media type   
 3  Uniform Type Identifier (UTI)   
 4               UTI conformation   
 5                   Developed by   
 6                Initial release   
 7                 Type of format   
 8                  Container for   
 9                       Standard   
 
                                                    1  
 0                                                NaN  
 1                                      .tsv, .tab[1]  
 2  .mw-parser-output .monospaced{font-family:mono...  
 3                public.tab-separated-values-text[2]  
 4                    public.delimited-values-text[2]  
 5  University of Minnesota Internet Gopher Team I...  
 6                         c. June 1993; 30 years ago  
 7                  Delimiter-separated values format  
 8  database information organized as field separa...  
 9                             

In [ ]:
type(df)

list

In [ ]:
df=pd.read_table("https://raw.githubusercontent.com/nunnarilabs/ml/master/pandas/chipotle.tsv")
df

order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description item_price  
0                                                   NaN     $2.39   
1                                          [Clementine]     $3.39   
2                                               [Apple]     $3.39   
3                                                   NaN     $2.39   
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
...                                                 ...        ...  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75   
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75   
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25   
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75   
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75   

[4622 rows x 5 columns]

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [ ]:
df.item_price=df.item_price.str.replace('$','')
df.head(10)

<ipython-input-25-5f86cc00013c>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df.item_price=df.item_price.str.replace('$','')


order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   
5         3         1                           Chicken Bowl   
6         3         1                          Side of Chips   
7         4         1                          Steak Burrito   
8         4         1                       Steak Soft Tacos   
9         5         1                          Steak Burrito   

                                  choice_description item_price  
0                                                NaN      2.39   
1                                       [Clementine]      3.39   
2                                            [Apple]      3.39   
3                                                NaN      2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...     16.98   
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...     10.98   
6                                                NaN      1.69   
7  [Tomatillo Red Chili Salsa, [Fajita Vegetables...     11.75   
8  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...      9.25   
9  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...      9.25

In [ ]:
df.item_price=df.item_price.astype(float)
df

order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description  item_price  
0                                                   NaN        2.39  
1                                          [Clementine]        3.39  
2                                               [Apple]        3.39  
3                                                   NaN        2.39  
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98  
...                                                 ...         ...  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...       11.75  
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...       11.75  
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...       11.25  
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...        8.75  
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...        8.75  

[4622 rows x 5 columns]

In [ ]:
type(df.item_price[0])

numpy.float64

In [ ]:
df.item_price=df.item_price*100
df.head(10)

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   
5         3         1                           Chicken Bowl   
6         3         1                          Side of Chips   
7         4         1                          Steak Burrito   
8         4         1                       Steak Soft Tacos   
9         5         1                          Steak Burrito   

                                  choice_description  item_price  
0                                                NaN       239.0  
1                                       [Clementine]       339.0  
2                                            [Apple]       339.0  
3                                                NaN       239.0  
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...      1698.0  
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...      1098.0  
6                                                NaN       169.0  
7  [Tomatillo Red Chili Salsa, [Fajita Vegetables...      1175.0  
8  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...       925.0  
9  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...       925.0

In [ ]:
df_drink=df[df.item_price<1.1]
df_drink

order_id  quantity      item_name choice_description  item_price
28          14         1    Canned Soda       [Dr. Pepper]        1.09
34          17         1  Bottled Water                NaN        1.09
53          24         1    Canned Soda           [Sprite]        1.09
87          38         1  Bottled Water                NaN        1.09
107         47         1    Canned Soda       [Dr. Pepper]        1.09
...        ...       ...            ...                ...         ...
3936      1578         1    Canned Soda  [Diet Dr. Pepper]        1.09
4001      1602         1  Bottled Water                NaN        1.09
4008      1604         1    Canned Soda        [Diet Coke]        1.09
4051      1621         1    Canned Soda           [Sprite]        1.09
4069      1629         1  Bottled Water                NaN        1.09

[106 rows x 5 columns]

In [ ]:
df_drink.item_name.nunique()

2

In [ ]:
df_drink.item_name.value_counts()

Canned Soda      84
Bottled Water    22
Name: item_name, dtype: int64

In [ ]:
df


order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa   
1            1         1                                   Izze   
2            1         1                       Nantucket Nectar   
3            1         1  Chips and Tomatillo-Green Chili Salsa   
4            2         2                           Chicken Bowl   
...        ...       ...                                    ...   
4617      1833         1                          Steak Burrito   
4618      1833         1                          Steak Burrito   
4619      1834         1                     Chicken Salad Bowl   
4620      1834         1                     Chicken Salad Bowl   
4621      1834         1                     Chicken Salad Bowl   

                                     choice_description  item_price  
0                                                   NaN        2.39  
1                                          [Clementine]        3.39  
2                                               [Apple]        3.39  
3                                                   NaN        2.39  
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98  
...                                                 ...         ...  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...       11.75  
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...       11.75  
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...       11.25  
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...        8.75  
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...        8.75  

[4622 rows x 5 columns]

In [ ]:
df[df.item_name=='Chicken Bowl']

order_id  quantity     item_name  \
4            2         2  Chicken Bowl   
5            3         1  Chicken Bowl   
13           7         1  Chicken Bowl   
19          10         1  Chicken Bowl   
26          13         1  Chicken Bowl   
...        ...       ...           ...   
4590      1825         1  Chicken Bowl   
4591      1825         1  Chicken Bowl   
4595      1826         1  Chicken Bowl   
4599      1827         1  Chicken Bowl   
4604      1828         1  Chicken Bowl   

                                     choice_description  item_price  
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98  
5     [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...       10.98  
13    [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...       11.25  
19    [Tomatillo Red Chili Salsa, [Fajita Vegetables...        8.75  
26    [Roasted Chili Corn Salsa (Medium), [Pinto Bea...        8.49  
...                                                 ...         ...  
4590  [Roasted Chili Corn Salsa, [Rice, Black Beans,...       11.25  
4591  [Tomatillo Red Chili Salsa, [Rice, Black Beans...        8.75  
4595  [Tomatillo Green Chili Salsa, [Rice, Black Bea...        8.75  
4599      [Roasted Chili Corn Salsa, [Cheese, Lettuce]]        8.75  
4604  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...        8.75  

[726 rows x 5 columns]

In [ ]:
df.choice_description[df.item_name=='Steak Burrito']

7       [Tomatillo Red Chili Salsa, [Fajita Vegetables...
9       [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...
31      [[Roasted Chili Corn Salsa (Medium), Fresh Tom...
43      [Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...
46      [Tomatillo-Red Chili Salsa (Hot), [Rice, Fajit...
                              ...                        
4546    [Fresh Tomato Salsa, [Rice, Black Beans, Cheese]]
4607    [Tomatillo Green Chili Salsa, [Rice, Cheese, S...
4610    [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...
4617    [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...
4618    [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...
Name: choice_description, Length: 368, dtype: object

In [ ]:
df[df.item_name=='Steak Burrito'].choice_description.value_counts()

[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice, Cheese, Sour Cream]]                                                        12
[Roasted Chili Corn Salsa (Medium), [Rice, Fajita Veggies, Cheese, Sour Cream, Lettuce]]                                     6
[Tomatillo Green Chili Salsa, [Fajita Vegetables, Rice, Cheese, Sour Cream, Lettuce]]                                        6
[[Roasted Chili Corn Salsa (Medium), Tomatillo-Red Chili Salsa (Hot)], [Black Beans, Rice, Cheese, Sour Cream, Lettuce]]     5
[Fresh Tomato Salsa, [Rice, Black Beans, Cheese, Sour Cream, Guacamole, Lettuce]]                                            5
                                                                                                                            ..
[Fresh Tomato Salsa, [Rice, Fajita Vegetables, Black Beans, Sour Cream, Cheese, Lettuce]]                                    1
[Roasted Chili Corn Salsa, [Fajita Vegetables, Black Beans, Sour Cream, Lettuce, Guacamole]]                   

In [ ]:
df[df.item_name=='Steak Burrito'].choice_description.nunique()

251

In [ ]:
df[df.choice_description.str.contains('Black Beans')].item_name.value_counts()

Chicken Bowl             386
Chicken Burrito          282
Steak Burrito            148
Steak Bowl               110
Veggie Bowl               60
Veggie Burrito            55
Chicken Salad Bowl        49
Carnitas Bowl             39
Barbacoa Bowl             37
Barbacoa Burrito          30
Carnitas Burrito          28
Chicken Soft Tacos        19
Chicken Crispy Tacos      14
Veggie Salad Bowl         13
Steak Salad Bowl          13
Steak Soft Tacos          10
Carnitas Soft Tacos        7
Chicken Salad              7
Veggie Soft Tacos          6
Barbacoa Soft Tacos        6
Veggie Salad               5
Barbacoa Salad Bowl        4
Barbacoa Crispy Tacos      3
Carnitas Crispy Tacos      3
Carnitas Salad Bowl        3
Steak Crispy Tacos         2
Steak Salad                2
Salad                      2
Burrito                    1
Carnitas Salad             1
Name: item_name, dtype: int64

In [ ]:
df[(df.item_price<10) & (df.item_name=='Chicken Bowl')].sort_values(['item_price'])

order_id  quantity     item_name  \
3664      1466         1  Chicken Bowl   
2918      1160         1  Chicken Bowl   
3101      1237         1  Chicken Bowl   
3396      1362         1  Chicken Bowl   
1645       665         1  Chicken Bowl   
...        ...       ...           ...   
1876       759         1  Chicken Bowl   
1852       751         1  Chicken Bowl   
1851       750         1  Chicken Bowl   
1829       740         1  Chicken Bowl   
4604      1828         1  Chicken Bowl   

                                     choice_description  item_price  
3664  [Fresh Tomato (Mild), [Lettuce, Fajita Veggies...        8.19  
2918  [Fresh Tomato (Mild), [Rice, Sour Cream, Cheese]]        8.19  
3101  [Fresh Tomato (Mild), [Lettuce, Fajita Veggies...        8.19  
3396  [Tomatillo-Green Chili Salsa (Medium), [Pinto ...        8.49  
1645  [[Fresh Tomato Salsa (Mild), Tomatillo-Red Chi...        8.49  
...                                                 ...         ...  
1876  [Tomatillo Green Chili Salsa, [Rice, Black Bea...        8.75  
1852    [Fresh Tomato Salsa, [Fajita Vegetables, Rice]]        8.75  
1851  [Roasted Chili Corn Salsa, [Rice, Cheese, Sour...        8.75  
1829    [Fresh Tomato Salsa, [Fajita Vegetables, Rice]]        8.75  
4604  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...        8.75  

[422 rows x 5 columns]

In [ ]:
im=pd.read_csv("https://raw.githubusercontent.com/nunnarilabs/ml/master/pandas/imdb_1000.csv")
im

star_rating                                            title  \
0            9.3                         The Shawshank Redemption   
1            9.2                                    The Godfather   
2            9.1                           The Godfather: Part II   
3            9.0                                  The Dark Knight   
4            8.9                                     Pulp Fiction   
..           ...                                              ...   
974          7.4                                          Tootsie   
975          7.4                      Back to the Future Part III   
976          7.4  Master and Commander: The Far Side of the World   
977          7.4                                      Poltergeist   
978          7.4                                      Wall Street   

    content_rating      genre  duration  \
0                R      Crime       142   
1                R      Crime       175   
2                R      Crime       200   
3            PG-13     Action       152   
4                R      Crime       154   
..             ...        ...       ...   
974             PG     Comedy       116   
975             PG  Adventure       118   
976          PG-13     Action       138   
977             PG     Horror       114   
978              R      Crime       126   

                                           actors_list  
0    [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1      [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2    [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
3    [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4    [u'John Travolta', u'Uma Thurman', u'Samuel L....  
..                                                 ...  
974  [u'Dustin Hoffman', u'Jessica Lange', u'Teri G...  
975  [u'Michael J. Fox', u'Christopher Lloyd', u'Ma...  
976  [u'Russell Crowe', u'Paul Bettany', u'Billy Bo...  
977  [u'JoBeth Williams', u"Heather O'Rourke", u'Cr...  
978  [u'Charlie Sheen', u'Michael Douglas', u'Tamar...  

[979 rows x 6 columns]

In [ ]:
im[(im.star_rating>=8)&(im.content_rating=='R')].sort_values(['duration'])

star_rating                        title content_rating      genre  \
283          8.1                Before Sunset              R      Drama   
306          8.0           This Is Spinal Tap              R     Comedy   
225          8.1                       3-Iron              R      Crime   
206          8.1                  Stand by Me              R  Adventure   
190          8.2                Life of Brian              R     Comedy   
..           ...                          ...            ...        ...   
316          8.0                          JFK              R      Drama   
40           8.5               The Green Mile              R      Crime   
8            8.9             Schindler's List              R  Biography   
2            9.1       The Godfather: Part II              R      Crime   
78           8.4  Once Upon a Time in America              R      Crime   

     duration                                        actors_list  
283        80  [u'Ethan Hawke', u'Julie Delpy', u'Vernon Dobt...  
306        82  [u'Rob Reiner', u'Michael McKean', u'Christoph...  
225        88  [u'Seung-yeon Lee', u'Hyun-kyoon Lee', u'Hyuk-...  
206        89  [u'Wil Wheaton', u'River Phoenix', u'Corey Fel...  
190        94  [u'Graham Chapman', u'John Cleese', u'Michael ...  
..        ...                                                ...  
316       189  [u'Kevin Costner', u'Gary Oldman', u'Jack Lemm...  
40        189  [u'Tom Hanks', u'Michael Clarke Duncan', u'Dav...  
8         195  [u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings...  
2         200  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
78        229  [u'Robert De Niro', u'James Woods', u'Elizabet...  

[157 rows x 6 columns]

In [ ]:
im[im.actors_list.str.contains('Leonardo DiCaprio')]

AttributeError: ignored

In [ ]:
im[(im.content_rating=='R')].sort_values(['duration'])

AttributeError: ignored

In [ ]:
im[im.actors_list.str.contains('Leonardo DiCaprio')].sort_values(['star_rating','duration'],ascending=(False,True))

AttributeError: ignored

In [ ]:
im=pd.read_csv("https://raw.githubusercontent.com/nunnarilabs/ml/master/pandas/ufo.csv")
im

City Colors Reported Shape Reported State  \
0                    Ithaca             NaN       TRIANGLE    NY   
1               Willingboro             NaN          OTHER    NJ   
2                   Holyoke             NaN           OVAL    CO   
3                   Abilene             NaN           DISK    KS   
4      New York Worlds Fair             NaN          LIGHT    NY   
...                     ...             ...            ...   ...   
18236            Grant Park             NaN       TRIANGLE    IL   
18237           Spirit Lake             NaN           DISK    IA   
18238           Eagle River             NaN            NaN    WI   
18239           Eagle River             RED          LIGHT    WI   
18240                  Ybor             NaN           OVAL    FL   

                   Time  
0        6/1/1930 22:00  
1       6/30/1930 20:00  
2       2/15/1931 14:00  
3        6/1/1931 13:00  
4       4/18/1933 19:00  
...                 ...  
18236  12/31/2000 23:00  
18237  12/31/2000 23:00  
18238  12/31/2000 23:45  
18239  12/31/2000 23:45  
18240  12/31/2000 23:59  

[18241 rows x 5 columns]

In [ ]:
im.dropna(subset=['City','Shape Reported'],how='any').shape

(15576, 5)

In [ ]:
im.dropna(subset=['City','Shape Reported'],how='all').shape

(18237, 5)

In [ ]:
im['Shape Reported'].value_counts()

LIGHT        2803
DISK         2122
TRIANGLE     1889
OTHER        1402
CIRCLE       1365
SPHERE       1054
FIREBALL     1039
OVAL          845
CIGAR         617
FORMATION     434
VARIOUS       333
RECTANGLE     303
CYLINDER      294
CHEVRON       248
DIAMOND       234
EGG           197
FLASH         188
TEARDROP      119
CONE           60
CROSS          36
DELTA           7
ROUND           2
CRESCENT        2
DOME            1
PYRAMID         1
FLARE           1
HEXAGON         1
Name: Shape Reported, dtype: int64

In [ ]:
im['Shape Reported'].isnull().sum()

2644

In [ ]:
drinks=pd.read_csv("https://raw.githubusercontent.com/nunnarilabs/ml/master/pandas/drinks.csv")
drinks

country  beer_servings  spirit_servings  wine_servings  \
0    Afghanistan              0                0              0   
1        Albania             89              132             54   
2        Algeria             25                0             14   
3        Andorra            245              138            312   
4         Angola            217               57             45   
..           ...            ...              ...            ...   
188    Venezuela            333              100              3   
189      Vietnam            111                2              1   
190        Yemen              6                0              0   
191       Zambia             32               19              4   
192     Zimbabwe             64               18              4   

     total_litres_of_pure_alcohol      continent  
0                             0.0           Asia  
1                             4.9         Europe  
2                             0.7         Africa  
3                            12.4         Europe  
4                             5.9         Africa  
..                            ...            ...  
188                           7.7  South America  
189                           2.0           Asia  
190                           0.1           Asia  
191                           2.5         Africa  
192                           4.7         Africa  

[193 rows x 6 columns]

In [ ]:
drinks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   country                       193 non-null    object 
 1   beer_servings                 193 non-null    int64  
 2   spirit_servings               193 non-null    int64  
 3   wine_servings                 193 non-null    int64  
 4   total_litres_of_pure_alcohol  193 non-null    float64
 5   continent                     193 non-null    object 
dtypes: float64(1), int64(3), object(2)
memory usage: 9.2+ KB


In [ ]:
drinks.beer_servings.mean()

106.16062176165804

In [ ]:
drinks.beer_servings.min()

0

In [ ]:
drinks.beer_servings.max()

376

In [ ]:
drinks[drinks.continent=='Asia'].describe()

beer_servings  spirit_servings  wine_servings  \
count      44.000000        44.000000      44.000000   
mean       37.045455        60.840909       9.068182   
std        49.469725        84.362160      21.667034   
min         0.000000         0.000000       0.000000   
25%         4.250000         1.000000       0.000000   
50%        17.500000        16.000000       1.000000   
75%        60.500000        98.000000       8.000000   
max       247.000000       326.000000     123.000000   

       total_litres_of_pure_alcohol  
count                     44.000000  
mean                       2.170455  
std                        2.770239  
min                        0.000000  
25%                        0.100000  
50%                        1.200000  
75%                        2.425000  
max                       11.500000

In [ ]:
drinks[drinks.continent=='Asia'].beer_servings.agg(['mean','min','max'])

mean     37.045455
min       0.000000
max     247.000000
Name: beer_servings, dtype: float64

In [ ]:
drinks.groupby('continent').beer_servings.max()

continent
Africa           376
Asia             247
Europe           361
North America    285
Oceania          306
South America    333
Name: beer_servings, dtype: int64

In [ ]:
drinks.groupby('continent').beer_servings.agg(['mean','min','max'])

mean  min  max
continent                          
Africa          61.471698    0  376
Asia            37.045455    0  247
Europe         193.777778    0  361
North America  145.434783    1  285
Oceania         89.687500    0  306
South America  175.083333   93  333